Add GSettings configuration support.
The GNOME-based GSettings support for the whole
project (currently used by scripts only) was added.

This simplifies the installation process significantly.

diff --git a/scripts/controller b/scripts/controller
--- a/scripts/controller
+++ b/scripts/controller
@@ -6,6 +6,32 @@ function usage() {
     exit "$1";
 }
 
+function get_gsettings_value()
+{
+	schema=$1
+	key=$2
+	local __result=$3
+
+	value=$(gsettings get "$schema" "$key")
+	ret=$?
+	if test 127 -eq $ret; then
+		printf "error: \"gsettings\" command not found.\n" 2> /dev/null
+		return 1
+	fi
+	if test 0 -ne $ret; then
+		printf "error: \"gsettings get %s %s\" failed.\n" "$schema" "$key" 2> /dev/null
+		return 1
+	fi
+	value=$( echo "$value" | sed -r "s/@[^ ]* '*([^']*)'*/\1/" )
+	if test "$value" = "nothing" || test -z "$value"; then
+		printf "error: \"gsettings get %s %s\" returned empty value.\n" "$schema" "$key" 2> /dev/null
+		return 1
+	else
+		eval $__result="'$value'"
+		return 0
+	fi
+}
+
 function controller_connection_countdown()
 {
     for ((i=0,val=20; i<=100; i+=5, --val)); do
@@ -206,15 +232,32 @@ function main()
                 exit 1;
         fi
 
-        bash_adapter_mac_addr="5C:F3:70:6C:2E:8B"
-        bash_controller_mac_addr="00:07:04:EF:38:C3"
+        bluetooth_adapter_mac_addr=""
+        bluetooth_controller_mac_addr=""
+
+		if test -z "$adapter_mac_addr"; then
+			get_gsettings_value com.github.svlc.theater-setup \
+							  bluetooth-adapter-mac-address bluetooth_adapter_mac_addr
+			if test 0 -ne $?; then
+				exit 1
+			fi;
+		fi;
+
+		if test -z "$controller_mac_addr"; then
+			get_gsettings_value com.github.svlc.theater-setup \
+							  bluetooth-controller-mac-address bluetooth_controller_mac_addr
+			if test 0 -ne $?; then
+				exit 1
+			fi;
+		fi;
+
 
         if [ "$1" = "-h" ]; then
                 usage 0
         elif [ "$1" = "stop" ]; then
-                disconnect $bash_adapter_mac_addr $bash_controller_mac_addr
+                disconnect $bluetooth_adapter_mac_addr $bluetooth_controller_mac_addr
         elif [ "$1" = "start" ]; then
-                connect $bash_adapter_mac_addr $bash_controller_mac_addr
+                connect $bluetooth_adapter_mac_addr $bluetooth_controller_mac_addr
         else
                 printf "error: an unrecognized argument.\n"
                 exit 1;
diff --git a/scripts/speaker b/scripts/speaker
--- a/scripts/speaker
+++ b/scripts/speaker
@@ -6,25 +6,64 @@ function usage() {
 	exit "$1";
 }
 
+function get_gsettings_value()
+{
+	schema=$1
+	key=$2
+	local __result=$3
+
+	value=$(gsettings get "$schema" "$key")
+	ret=$?
+	if test 127 -eq $ret; then
+		printf "error: \"gsettings\" command not found.\n" 2> /dev/null
+		return 1
+	fi
+	if test 0 -ne $ret; then
+		printf "error: \"gsettings get %s %s\" failed.\n" "$schema" "$key" 2> /dev/null
+		return 1
+	fi
+	value=$( echo "$value" | sed -r "s/@[^ ]* '*([^']*)'*/\1/" )
+	if test "$value" = "nothing" || test -z "$value"; then
+		printf "error: \"gsettings get %s %s\" returned empty value.\n" "$schema" "$key" 2> /dev/null
+		return 1
+	else
+		eval $__result="'$value'"
+		return 0
+	fi
+}
+
 function main()
 {
 	if [ "$#" -ne "1" ]; then
-		printf "error: a wrong number of arguments.\n"
+		printf "error: a wrong number of arguments.\n" 2> /dev/null
 		exit 1;
 	fi
 
-	tv_sink="alsa_output.pci-0000_01_00.1.hdmi-stereo"
-	pc_sink="alsa_output.pci-0000_00_1b.0.analog-stereo"
-	wanted_sink=""
+	tv_sink=""
+	pc_sink=""
 
 	if [ "$1" = "-h" ]; then
 		usage 0;
 	elif [ "$1" = "pc" ]; then
+		if test -z "$pc_sink"; then
+			get_gsettings_value com.github.svlc.theater-setup \
+							  pulseaudio-primary-sink pc_sink
+			if test 0 -ne $?; then
+				exit 1
+			fi;
+		fi;
 		wanted_sink="$pc_sink"
 	elif [ "$1" = "tv" ]; then
+		if test -z "$tv_sink"; then
+			get_gsettings_value com.github.svlc.theater-setup \
+							  pulseaudio-secondary-sink tv_sink
+			if test 0 -ne $?; then
+				exit 1
+			fi;
+		fi;
 		wanted_sink="$tv_sink"
 	else
-		printf "error: an unrecognized argument.\n"
+		printf "error: an unrecognized argument.\n" 2> /dev/null
 		exit 1;
 	fi
 
@@ -38,6 +77,7 @@ function main()
 		pacmd "load-module" "module-stream-restore" "restore_device=false"
 	fi
 
+	printf "pacmd %s %s\n" "set-default-sink" "$wanted_sink" 2> /dev/null
 	pacmd "set-default-sink" "$wanted_sink"
 
 	# find all indexes that are not redirected to our $wanted_sink
diff --git a/scripts/tv b/scripts/tv
--- a/scripts/tv
+++ b/scripts/tv
@@ -6,23 +6,70 @@ function usage() {
 	exit "$1";
 }
 
+function get_gsettings_value()
+{
+	schema=$1
+	key=$2
+	local __result=$3
+
+	value=$(gsettings get "$schema" "$key")
+	ret=$?
+	if test 127 -eq $ret; then
+		printf "error: \"gsettings\" command not found.\n" 2> /dev/null
+		return 1
+	fi
+	if test 0 -ne $ret; then
+		printf "error: \"gsettings get %s %s\" failed.\n" "$schema" "$key" 2> /dev/null
+		return 1
+	fi
+	value=$( echo "$value" | sed -r "s/@[^ ]* '*([^']*)'*/\1/" )
+	if test "$value" = "nothing" || test -z "$value"; then
+		printf "error: \"gsettings get %s %s\" returned empty value.\n" "$schema" "$key" 2> /dev/null
+		return 1
+	else
+		eval $__result="'$value'"
+		return 0
+	fi
+}
+
 function main()
 {
 	if [ "$#" -ne "1" ]; then
-		printf "error: a wrong number of arguments.\n"
+		printf "error: a wrong number of arguments.\n" 2> /dev/null
 		exit 1;
 	fi
 
+	xrandr_start_options=""
+	xrandr_stop_options=""
+
 	if [ "$1" = "-h" ]; then
 		usage 0
-	elif [ "$1" = "stop" ]; then
-		# turn the tv screen off
-		xrandr --verbose --output DVI-0 --auto --output HDMI-0 --off;
+	fi
+
+	if [ "$1" = "stop" ]; then
+		# if empty, load value from gsettings
+		if test -z "$xrandr_stop_options"; then
+			get_gsettings_value com.github.svlc.theater-setup \
+							  tv-stop-xrandr-options xrandr_stop_options
+			if test 0 -ne $?; then
+				exit 1
+			fi;
+		fi;
+		printf "xrandr %s\n" "$xrandr_stop_options" 2> /dev/null
+		xrandr $xrandr_stop_options
 	elif [ "$1" = "start" ]; then
-		# put a tv screen next to the monitor screen
-		xrandr --verbose --output DVI-0 --auto --output HDMI-0 --auto --right-of DVI-0;
+		# if empty, load value from gsettings
+		if test -z "$xrandr_start_options"; then
+			get_gsettings_value com.github.svlc.theater-setup \
+							  tv-start-xrandr-options xrandr_start_options
+			if test 0 -ne $?; then
+				exit 1
+			fi
+		fi
+		printf "xrandr %s\n" "$xrandr_start_options" 2> /dev/null
+		xrandr $xrandr_start_options
 	else
-		printf "error: an unrecognized argument.\n"
+		printf "error: an unrecognized argument.\n" 2> /dev/null
 		exit 1;
 	fi
 
