Rewrite the "controller" script
Now it should be much easier to read the script.

* fix help output (--help)
* fix indentation (mixing of tabs and spaces)
* take advantage of some tcl's features (procedures, lists, ...)

diff --git a/scripts/controller b/scripts/controller
--- a/scripts/controller
+++ b/scripts/controller
@@ -1,151 +1,199 @@
 #! /usr/bin/env bash
 
 function usage() {
-	printf "Turn the tv connection on/off by invoking xrandr command.\n"
-	printf "Usage: %s [start|stop]\n" "$(basename "$0")";
-	exit "$1";
+    printf "Turn the bluetooth controller connection  on/off\n"
+    printf "Usage: %s [start|stop]\n" "$(basename "$0")";
+    exit "$1";
+}
+
+function controller_connection_countdown()
+{
+    for ((i=0,val=20; i<=100; i+=5, --val)); do
+        echo "$i"
+        echo "# Turn the controller on.\n $val";
+        sleep 1;
+    done | zenity --progress --title="Request" --text="Turn the controller on." --percentage="0" --auto-close
+
+    return $?
+}
+
+function run_expect()
+{
+    bash_adapter_mac_addr="$1"
+    bash_controller_mac_addr="$2"
+    bash_proc_name="$3"
+
+    expect <<EOF
+
+    proc check_and_select_adapter {adapter_mac_addr controller_mac_addr} {
+
+        set timeout 3
+
+        expect {
+            -re "\$adapter_mac_addr.*" { }
+            default {
+                spawn zenity --timeout=10 --info "--text=Bluetooth adapter with MAC address \"\$adapter_mac_addr\" is not present.";
+                wait
+                return 1
+            }
+        }
+
+        send "select \$adapter_mac_addr\r"
+        sleep 0.5
+
+        return 0
+    }
+
+    proc disconnect {adapter_mac_addr controller_mac_addr spawn_id} {
+
+        set timeout 2
+
+        send "info \$controller_mac_addr\r"
+        expect {
+            -re "Connected: no.*" { spawn zenity --timeout=10 --info "--text=Controller is already disconnected."; wait; return 1; }
+            -re "Connected: yes.*" { }
+        }
+
+        set timeout 8
+        send "disconnect \$controller_mac_addr\r"
+
+        expect {
+            -re "Connected: no.*" { spawn zenity --timeout=10 --info "--text=Controller disconnected."; }
+            default {
+                spawn zenity --timeout=10 --info "--text=Disconnecting of the controller failed.";
+                wait
+                return 1
+            }
+        }
+        send "quit\r"
+        expect eof
+        return 0;
+    }
+
+    proc connect {adapter_mac_addr controller_mac_addr spawn_id} {
+
+        set timeout 2
+
+        send "power on\r"
+        expect {
+            -re "succeeded.*" { }
+            default {
+                spawn zenity --timeout=10 --info "--text=\"Power on\" command failed.";
+                wait
+                return 1
+            }
+        }
+
+        send "info \$controller_mac_addr\r"
+        expect {
+            -re "Connected: no.*" { }
+            -re "Connected: yes.*" {
+                spawn zenity --timeout=10 --info "--text=Controller is already connected!";
+                wait
+                return 1
+            }
+        }
+
+        send "agent on\r"
+        expect {
+            -re "registered.*" { }
+            default {
+                spawn zenity --timeout=10 --info "--text=\"Power on\" command failed.";
+                wait
+                return 1
+            }
+        }
+
+        send "default-agent\r"
+        expect {
+            -re "successful.*" { }
+            default {
+                spawn zenity --timeout=10 --info "--text=\"default-agent\" command failed.";
+                wait
+                return 1
+            }
+        }
+
+        # save "spawn_id" of the main process
+        set spawn_id_main \$spawn_id
+        spawn bash -c controller_connection_countdown;
+
+        set spawn_id_bash \$spawn_id;
+        set spawn_id_zenity "";
+
+        set count 10;
+        set timeout 1;
+
+        while {1} {
+            set spawn_id \$spawn_id_bash
+            expect {
+                eof {
+                    lassign [wait] pid sp_id os_error status
+                    if { \$os_error != 0 || \$status != 0 } {
+                        set spawn_id \$spawn_id_main;
+                        return 1;
+                    }
+                }
+            }
+            
+            set spawn_id \$spawn_id_main
+            expect {
+                -re "Connected: yes.*" {
+                    close -i \$spawn_id_bash;
+                    wait -i \$spawn_id_bash;
+
+                    spawn zenity --timeout=20 --info "--text=Connection is on.";
+                    set spawn_id_zenity \$spawn_id
+                    set spawn_id \$spawn_id_main
+                    break;
+                }
+            }
+            incr count -1
+            if { \$count == 0 } {
+                spawn zenity --timeout=10 --info "--text=Time is out, connection failed. Try again.";
+                set spawn_id_zenity \$spawn_id
+                set spawn_id \$spawn_id_main
+                break;
+            }
+        }
+
+        send "quit\r"
+        expect eof
+        wait -i \$spawn_id_zenity;
+        return 0;
+    }
+
+    set adapter_mac_addr $bash_adapter_mac_addr
+    set controller_mac_addr $bash_controller_mac_addr;
+
+    spawn bluetoothctl;
+
+    set ret [ check_and_select_adapter \$adapter_mac_addr \$controller_mac_addr ];
+    if {\$ret != 0} {
+        exit \$ret;
+    }
+
+    set ret [ $bash_proc_name \$adapter_mac_addr \$controller_mac_addr \$spawn_id ];
+    exit \$ret;
+
+EOF
 }
 
 function connect()
 {
-	bt_card_mac_addr=$1
-	controller_mac_addr=$2
-
-	expect <<EOF
-
-spawn bluetoothctl
-
-set timeout 3
-
-expect {
-    -re "$bt_card_mac_addr.*" { return; }
-    default {
-	spawn zenity --timeout=10 --info "--text=Bluetooth adapter with MAC address \"$bt_card_mac_addr\" is not present.";
-	wait
-	exit 1
-    }
-}
-
-send "select $bt_card_mac_addr\r"
-sleep 0.5
-
-send "power on\r"
-expect {
-    -re "succeeded.*" { return; }
-    default {
-	spawn zenity --timeout=10 --info "--text=\"Power on\" command failed.";
-	wait
-	exit 1
-    }
-}
-
-send "info $controller_mac_addr\r"
-expect {
-    -re "Connected: no.*" { return; }
-    -re "Connected: yes.*" {
-	spawn zenity --timeout=10 --info "--text=Controller is already connected!";
-	wait
-	exit 1
-    }
-}
-
-send "agent on\r"
-expect {
-    -re "registered.*" { return; }
-    default {
-	spawn zenity --timeout=10 --info "--text=\"Power on\" command failed.";
-	wait
-	exit 1
-    }
-}
-
-send "default-agent\r"
-expect {
-    -re "successful.*" { return; }
-    default {
-	spawn zenity --timeout=10 --info "--text=\"default-agent\" command failed.";
-	wait
-	exit 1
-    }
-}
-
-set spawn_id_main \$spawn_id
-
-spawn zenity --timeout=20 --info "--text=Turn the controller on."
-
-set spawn_id_zenity \$spawn_id
-set spawn_id \$spawn_id_main
-
-set timeout 20
-expect {
-    -re "Connected: yes.*" 
-    {
-	close -i \$spawn_id_zenity;
-	wait -i \$spawn_id_zenity;
-
-	spawn zenity --timeout=20 --info "--text=Connection is on.";
-	set spawn_id_zenity \$spawn_id
-	set spawn_id \$spawn_id_main
-	return;
-    }
-    default {
-	spawn zenity --timeout=10 --info "--text=Time is out, connection failed. Try again.";
-	wait
-	exit 1
-    }
-}
-
-send "quit\r"
-expect eof
-wait -i \$spawn_id_zenity;
-
-EOF
-
-
-	if [ "$?" -eq 0 ]; then
-		antimicro --tray --profile /usr/local/etc/antimicro_controller.amgp &
-	fi
+    export -f controller_connection_countdown;
+    run_expect $1 $2 "connect"
+    
+    if [ "$?" -eq "0" ]; then
+        antimicro --tray --profile /usr/local/etc/antimicro_controller.amgp &
+    fi
 }
 
 function disconnect()
 {
-    bt_card_mac_addr=$1
-    controller_mac_addr=$2
+    run_expect $1 $2 "disconnect"
 
-    expect <<EOF
-
-spawn bluetoothctl
-
-
-set timeout 3
-expect {
-    -re "$bt_card_mac_addr.*" { return; }
-    default {
-	spawn zenity --timeout=10 --info "--text=Bluetooth adapter with MAC address \"$bt_card_mac_addr\" is not present.";
-	wait
-	exit 1
-    }
-}
-
-sleep 0.5
-set timeout 8
-send "disconnect $controller_mac_addr\r"
-
-expect {
-    -re "Connected: no.*" { spawn zenity --timeout=10 --info "--text=Controller disconnected."; }
-    default {
-	spawn zenity --timeout=10 --info "--text=Disconnecting of the controller failed.";
-	wait
-	exit 1
-    }
-}
-
-send "quit\r"
-expect eof
-
-EOF
-
-	if [ -n "$(pgrep antimicro)" ]; then
+    if [ -n "$(pgrep antimicro)" ]; then
         killall antimicro;
     fi;
 
@@ -153,24 +201,24 @@ EOF
 
 function main()
 {
-	if [ "$#" -ne "1" ]; then
-		printf "error: a wrong number of arguments.\n"
-		exit 1;
-	fi
+        if [ "$#" -ne "1" ]; then
+                printf "error: a wrong number of arguments.\n"
+                exit 1;
+        fi
 
-	bt_card_mac_addr="5C:F3:70:6C:2E:8B"
-	controller_mac_addr="00:07:04:EF:38:C3"
+        bash_adapter_mac_addr="5C:F3:70:6C:2E:8B"
+        bash_controller_mac_addr="00:07:04:EF:38:C3"
 
-	if [ "$1" = "-h" ]; then
-		usage 0
-	elif [ "$1" = "stop" ]; then
-		disconnect $bt_card_mac_addr $controller_mac_addr
-	elif [ "$1" = "start" ]; then
-		connect $bt_card_mac_addr $controller_mac_addr
-	else
-		printf "error: an unrecognized argument.\n"
-		exit 1;
-	fi
+        if [ "$1" = "-h" ]; then
+                usage 0
+        elif [ "$1" = "stop" ]; then
+                disconnect $bash_adapter_mac_addr $bash_controller_mac_addr
+        elif [ "$1" = "start" ]; then
+                connect $bash_adapter_mac_addr $bash_controller_mac_addr
+        else
+                printf "error: an unrecognized argument.\n"
+                exit 1;
+        fi
 }
 
 main "$@"
